all:
	gcc -funroll-loops -fprefetch-loop-arrays -maccumulate-outgoing-args -o ../../target/game  game.c  max_rank_of_poker.c \
	 msg_to_bit.c  player.c  poker_decision.c  rank_of_poker.c  money.c -lm
